name: hospital_management_system
description: Group 50 Project Capstone "Hospital Management System"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - images/a_dot_burr.jpeg


  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/font/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/font/OpenSans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/font/OpenSans/OpenSans-italic.ttf
          style: italic
        - asset: assets/font/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/font/OpenSans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/font/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/font/OpenSans/OpenSans-MediumItalic.ttf
          weight: 500
          style : italic
        - asset: assets/font/OpenSans/OpenSans-Regular.ttf
        - asset: assets/font/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/OpenSans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
    
  
